//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ttmain.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TTAUSWDLG                   101
#define IDR_MAINFRAME                   128
#define IDR_TTMAINTYPE                  129
#define IDI_TTMAIN                      131
#define IDD_KREISBERECHNUNG             132
#define IDD_TORWAHL_DLG                 134
#define IDR_TORVIEWMENU                 135
#define IDD_ZUSCHNITTREGELN_DLG         136
#define IDC_TTORTYP                     142
#define IDB_V_PROP                      142
#define IDC_FUELLUNG                    143
#define IDB_V_VALUE                     143
#define IDC_PROFILMASS                  144
#define IDC_ANZAHL                      146
#define IDC_BREITE                      147
#define IDC_HOEHE                       148
#define IDS_TTORTYP                     149
#define IDS_FUELLUNG                    150
#define IDC_BREITE_FL1                  151
#define IDC_KUNDE                       153
#define IDR_ZR_PROP_VALUE               153
#define IDC_GETEILT1                    154
#define IDC_OBERT1                      155
#define IDC_GETEILT2                    156
#define IDC_OBERT2                      157
#define IDC_GETEILT3                    158
#define IDC_OBERT3                      159
#define IDC_GETEILT4                    160
#define IDC_OBERT4                      161
#define IDC_GETEILT5                    162
#define IDC_OBERT5                      163
#define IDC_GLASART1                    164
#define IDC_GLASART2                    165
#define IDC_GLASART3                    166
#define IDD_ZR_NEU_DLG                  166
#define IDC_GLASART4                    167
#define IDC_GLASART5                    168
#define IDC_KOMMISSION                  169
#define IDC_OBERHOEHE                   170
#define IDC_OKF                         171
#define IDD_ZR_PROFILE_DLG              171
#define IDC_FENSTER1                    172
#define IDC_FENSTER2                    173
#define IDD_ZR_SF_DLG                   173
#define IDC_FENSTER3                    174
#define IDC_TT_HAND                     174
#define IDC_FENSTER4                    175
#define IDD_TEST_CONFIG_DLG             175
#define IDC_FENSTER5                    176
#define IDM_TESTSYSTEM                  176
#define IDC_SPROSSE1                    177
#define IDD_PROFIL_EDIT_DLG             177
#define IDC_SPROSSE2                    178
#define IDD_PROFILE_ELEM_DLG            178
#define IDC_SPROSSE3                    179
#define IDB_RP1087                      179
#define IDC_SPROSSE4                    180
#define IDC_SPROSSE5                    181
#define IDB_RPRR                        181
#define IDC_400R                        182
#define IDB_RP1093                      182
#define IDB_RP1094                      183
#define IDB_RP1348                      184
#define IDB_PROFIL_SENK                 185
#define IDB_PROFIL_WAAG                 186
#define IDB_RP6_8                       187
#define IDD_BH_PROFILE_DLG              188
#define IDD_BH_TEST                     189
#define IDD_BH_PROFIL_EDIT_DLG          190
#define IDR_HOLE_PROFILE                191
#define IDR_HP_POPUP                    198
#define IDB_BMTREEFIRST                 200
#define IDB_E_TYP                       201
#define IDB_E_ART                       202
#define IDB_E_RAHMEN                    203
#define IDB_E_FLUEGELANZ                204
#define IDB_E_OBERTEIL                  205
#define IDB_E_GETEILT                   206
#define IDB_E_OKF                       207
#define IDB_E_BOGEN                     208
#define IDB_W_TOR                       209
#define IDB_W_TUER                      210
#define IDB_W_STERN                     211
#define IDB_W_400                       212
#define IDB_W_600                       213
#define IDB_W_800                       214
#define IDB_W_RZ                        215
#define IDB_W_RR                        216
#define IDB_W_RW                        217
#define IDB_W_KEIN                      218
#define IDB_W_OZO                       219
#define IDB_W_OIF                       220
#define IDB_W_2                         221
#define IDB_W_3                         222
#define IDB_W_4                         223
#define IDB_W_5                         224
#define IDB_W_JA                        225
#define IDB_W_NEIN                      226
#define IDB_Z_WERT                      227
#define IDB_BMTREELAST                  227
#define IDC_RADIUS                      1000
#define IDC_SEHNE                       1001
#define IDC_SEHNENHOEHE                 1002
#define IDC_BOGENLAENGE                 1004
#define IDC_WINKEL                      1005
#define IDC_BWINKEL_MITTE               1005
#define IDC_RADIORADIUS                 1006
#define IDC_RADIOSEHNE                  1007
#define IDC_RADIOSEHNENHOEHE            1008
#define IDC_BWINKEL_AUSSEN              1009
#define IDC_SWINKEL_AUSSEN              1010
#define IDC_PROFILDICKE                 1012
#define IDC_BERECHNEWINKEL              1013
#define IDC_CIRCLE_HELP                 1014
#define IDC_BOGEN                       1015
#define IDC_TORLIST                     1017
#define IDC_ZUSCHNITTREGELN_TREE        1018
#define IDC_ZR_NEW_PROPERTY             1021
#define IDC_ZR_NEW_VALUE                1022
#define IDC_ZR_PROFILE_TREE             1023
#define IDC_EDIT1                       1024
#define IDC_ZR_SF_SENK                  1026
#define IDC_ZR_SF_QUER                  1027
#define IDC_LINK_MAIL                   1027
#define IDC_ZR_SF2_SENK                 1028
#define IDC_TEST_FILE                   1028
#define IDC_ZR_SF2_QUER                 1029
#define IDC_LOG_FILE                    1029
#define IDC_ZR_SF_SENK_400              1030
#define IDC_TEST_DIR                    1030
#define IDC_ZR_SF_QUER_400              1031
#define IDC_MANUAL                      1031
#define IDC_ZR_SF2_SENK_400             1032
#define IDC_ALWAYS_CONFIG               1032
#define IDC_ZR_SF2_QUER_400             1033
#define IDC_BREAK_ON_ERROR              1033
#define IDC_SHOW_LOG                    1034
#define IDC_TEST_PROFIL                 1035
#define IDC_TEST_FUELLUNG               1036
#define IDC_PROFIL_NEW                  1036
#define IDC_TEST_PROFIL600              1037
#define IDC_PROFIL_EDIT                 1037
#define IDC_BH_PROFIL_EDIT              1037
#define IDC_TEST_FUELLUNG600            1038
#define IDC_PROFIL_DEL                  1038
#define IDC_PROFILE_ELEM_COUNT          1039
#define IDC_PROFILE_ELEM_LENGTH         1041
#define IDC_PROFILE_ELEM_TYPE           1043
#define IDC_PROFILE_ORIENTATION         1044
#define IDC_PROFIL_LIST                 1044
#define IDC_BH_PROFIL_LIST              1045
#define ID_BH_TEST_COMPUTE              1046
#define IDC_BH_TEST_OFFSET_TO_HOLE      1047
#define IDC_BH_TEST_PROFIL_LENGTH       1048
#define IDC_BH_TEST_RESULT              1049
#define IDC_BH_TEST_NEW_OFFSET_TO_HOLE  1050
#define IDC_BH_PROFIL_NEW               1050
#define IDC_BH_PROFIL_DEL               1051
#define IDC_BH_PROFILE_ELEM_COUNT       1052
#define IDC_BH_PROFILE_ELEM_LENGTH      1053
#define IDC_BH_PROFIL_OPT               1054
#define IDC_BH_PROFIL_OPT_TIME          1055
#define ID_TOR_HINZU                    32771
#define ID_DATEI_FFNEN                  32772
#define ID_KREISBERECHNUNG              32773
#define ID_TOR_AENDERN_1                32780
#define ID_TOR_AENDERN_2                32781
#define ID_INHALT                       32782
#define ID_TOR_AENDERN                  32786
#define ID_PU_TOR_AENDERN               32787
#define ID_ZUSCHNITTDATEI_AUSLESEN      32788
#define ID_ZUSCHNITTREGELN_ANZEIGEN     32790
#define ID_ZR_PROP_VALUE_CHANGE         32791
#define ID_ZR_PROP_VALUE_NEW            32792
#define ID_ZR_PROP_VALUE_DELETE         32793
#define ID_ZUSCHNITTREGELN_SPEICHERN    32794
#define ID_ZUSCHNITTREGEL_FLUEGEL1      32796
#define ID_ZUSCHNITTREGEL_FLUEGEL2      32797
#define ID_ZUSCHNITTREGEL_FLUEGEL3      32798
#define ID_ZUSCHNITTREGEL_FLUEGEL4      32799
#define ID_ZUSCHNITTREGEL_FLUEGEL5      32800
#define ID_REFTOR_SPEICHERN             32802
#define ID_REFTOR_LADEN                 32803
#define ID_TEST_START                   32804
#define ID_TEST_STOP                    32805
#define ID_TEST_EINSTELLUNGEN           32806
#define IDC_PU_PROFILE_BEARBEITEN       32807
#define IDC_PROFILE_BEARBEITEN          32808
#define ID_BH_TEST                      32811
#define ID_HOLE_PROFILE_NEW             32812
#define ID_HP_AENDERN                   32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
